#!/usr/bin/env bash

# TODO local support for devs
# TODO gitlab support

program="bashget"
version=0.9.0
store="$HOME/.bashget"
cwd=$(pwd)

helpMessage="$(cat <<-EOF
${program} ${version}

bash scripts lite package manager

packages are store in ${store}

packages binaries are copied to $HOME/.local/bin


list installed package
----------------------

${program} ls


get package location
--------------------

. \$(${program} get package)/mylib.sh

add new package
---------------

${program} add package user [branch]

switchs and options:

to add package through ssh use the REPO_SSH variable:
REPO_SSH=1 ${program} get ...

to add package from other host than the default github.com, use the REPO_HOST variable:
REPO_HOST=gitlab.com ${program} add ...

binaries location:

if the repo contains files like [repo_name] and/or [repo_name].sh, they are copied to $HOME/.local/bin

if the repo contains a bin directory, files of this directory are copied to $HOME/.local/bin

update installed package
------------------------

${program} up package [branch]


update ALL installed packages
-----------------------------

${program} up --all


remove installed package
------------------------

${program} rm package

EOF
)"

log () {
    echo "${program} / $*"
}

fatal () {
    echo -e "\e[31m[FATAL] ${program} / $*. aborted\e[0m"
    exit 1
}

# check arg
# checkArg name var
checkArg () {
    if [ -z "$2" ]; then
      echo ""
      fatal "argument missing: $1"
   fi
}

# syncPackageBins package
syncPackageBins () {
    log "sync package bins" 
    local package="$1"
    checkArg package "${package}"

    # any script with repo name ? considered as main script, copy it to .local/bin
    [[ -f "${store}/${package}/${package}" ]] && cp "${store}/${package}/${package}" $HOME/.local/bin/ && chmod u+x "$HOME/.local/bin/${package}" || true
    [[ -f "${store}/${package}/${package}.sh" ]] && cp "${store}/${package}/${package}.sh" $HOME/.local/bin/ && chmod u+x "$HOME/.local/bin/${package}.sh" || true

    # copy all ./bin files to .local/bin
    [[ -d "${store}/${package}/bin" ]] && chmod u+x "${store}/${package}/bin/*" && cp "${store}/${package}/bin/*" $HOME/.local/bin/  || true
}


handler_help () {
    echo "${helpMessage}"
    exit 0
}

# ls
handler_ls () {
    ls -1 "${store}"
}

# get package
handler_get () {
    echo "${store}/$1"
}

# [REPO_HOST=host.com] [REPO_SSH=1] add package user [branch]
handler_add () {
    log "add"

    local package="$1"
    checkArg package "${package}"
    local user="$2"
    checkArg user "${user}"
    local branch="${3:-master}"
    local host="${REPO_HOST:-github.com}"
    local url
    [[ "${REPO_SSH}" == 1 ]] && url="git@${host}:${user}/${package}.git" || url="https://${host}/${user}/${package}.git"

    log "package: ${package}"
    log "user: ${user}"
    log "branch: ${branch}"
    log "host: ${host}"
    log "url: ${url}"

    if [[ -d "${store}/${package}" ]]; then
        log "package already installed: ${package}. applying update instead..."
        handler_up "${package}" "${branch}"
    else
        mkdir -p "${store}"
        git clone --depth=1 "${url}" -b "${branch}" "${store}/${package}"
        syncPackageBins "${package}"
    fi
}

# up package [branch]
handler_up () {
    log "update"

    local package="$1"
    checkArg package "${package}"
    local branch="${2:-master}"

    [[ "${package}" == "--all" ]] && updateAll || true

    log "package: ${package}"
    log "branch: ${branch}"

    [[ ! -d "${store}/${package}" ]] && fatal "package not found: ${package}. please use add command instead" || true

    # git pull local branch or create one from repo
    cd "${store}/${package}"
    git fetch origin
    git show-branch "${branch}" &>/dev/null && git pull origin "${branch}" || git checkout -b "${branch}" "origin/${branch}"

    cd "${cwd}"
    syncPackageBins "${package}"
}

updateAll () {
    log "update ALL"

    # set the packages to update list, from the store
    local packages=()
    cd "${store}"
    for p in *; do
        if [[ -d "$p" ]]; then
            packages+=("$p")
        fi
    done
    cd "${cwd}"
    log "packages to update: ${packages[*]}"

    # update packages
    for p in "${packages[@]}"
    do
        handler_up "$p"
    done

    exit 0
}

# rm package
handler_rm () {
    log "rm"

    local package="$1"
    checkArg package "${package}"

    log "package: ${package}"
    [[ ! -d "${store}/${package}" ]] && fatal "package not found: ${package}" || true

    rm -rf "${store}/${package}/"
    rm "$HOME/.local/bin/${package}.sh" 2> /dev/null || true
    rm "$HOME/.local/bin/${package}" 2> /dev/null || true
}


dispatch () {
    [[ -z "${store}" ]] && fatal "store path not defined" || true

    local command="$1"
    [[ -z "$1" ]] && handler_help || true

    declare -F "handler_${command}" &> /dev/null && "handler_${command}" ${@:2} || fatal "command not found or command error"
}

dispatch $@
